# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'tests'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - task: Docker@2
        displayName: Build and Run Tests
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/Tests/Dockerfile'
          tags: |
            $(tag)