# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: CmdLine@2
      inputs:
        script: |
          echo DEBUG
          pwd
          ll

    - task: CMake@1
      inputs:
        cmakeArgs: CMakeLists.txt -B ./build
    - task: CmdLine@2
      inputs:
        script: |
          echo Building WebXO
          cd build
          make all