# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push to Docker Hub
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'killerducks/webxo-server'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to App Services
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go(186c271c-7ff9-4937-8650-7816105c663c)'
        appType: 'webAppContainer'
        WebAppName: 'WebXO'
        deployToSlotOrASE: true
        ResourceGroupName: 'WebXO_RG'
        SlotName: 'production'
        DockerNamespace: 'https://index.docker.io'
        DockerRepository: 'killerducks/webxo-server'
        DockerImageTag: 'latest'    