# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: CmdLine@2
      inputs:
        script: |
          echo DEBUG
          pwd
          ls -la
          echo Making Build Directory
          mkdir build
          cd ./build
          echo Generating Build Files
          cmake -G "Unix Makefiles" ../
          cd ${System.DefaultWorkingDirectory}
          echo Current Directory
          pwd

    - task: CMake@1
      inputs:
        cmakeArgs: --build ./build --config Debug --target all -- -j 10
        workingDirectory: ${System.DefaultWorkingDirectory}
    - task: CmdLine@2
      inputs:
        script: |
          echo Testing WebXO
          cd build/ExE
          ./WebXOSrv_GTests