# AWS CodeBuild Build Spec for WebXO
# Author: KillerDucks
# Maintainer: MelissaXO
# Organization: Null

version: 0.2

phases:
    install:
      commands:
        - echo Nothing to do during the install phase
    pre_build:
      commands:
        - echo Running Pre Build phase
        - apt-get update
        - apt-get install -y build-essential cmake zlib1g-dev libgtest-dev        
        - RPATH=$(pwd)
        
        - echo Installing GTest
        - cd /usr/src/gtest
        - cmake CMakeLists.txt
        - make
        - cp *.a /usr/lib
        - cd $RPATH

        - echo Running CMake Build Generator        
        - mkdir ./build
        - cd ./build
        - cmake -G "Unix Makefiles" ../
        - cd ../
        - echo Pre Build phase completed
    build:
      commands:
        - cmake --build ./build --config Debug --target clean --
    post_build:
        commands:
          - echo Build completed on `date`
        