# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/melissa/GCXX/WebXO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/melissa/GCXX/WebXO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/melissa/GCXX/WebXO/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/melissa/GCXX/WebXO/CMakeFiles /home/melissa/GCXX/WebXO/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/melissa/GCXX/WebXO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WebXO

# Build rule for target.
WebXO: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WebXO
.PHONY : WebXO

# fast build rule for target.
WebXO/fast:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/build
.PHONY : WebXO/fast

src/WebXLib/Compression.o: src/WebXLib/Compression.cpp.o

.PHONY : src/WebXLib/Compression.o

# target to build an object file
src/WebXLib/Compression.cpp.o:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Compression.cpp.o
.PHONY : src/WebXLib/Compression.cpp.o

src/WebXLib/Compression.i: src/WebXLib/Compression.cpp.i

.PHONY : src/WebXLib/Compression.i

# target to preprocess a source file
src/WebXLib/Compression.cpp.i:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Compression.cpp.i
.PHONY : src/WebXLib/Compression.cpp.i

src/WebXLib/Compression.s: src/WebXLib/Compression.cpp.s

.PHONY : src/WebXLib/Compression.s

# target to generate assembly for a file
src/WebXLib/Compression.cpp.s:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Compression.cpp.s
.PHONY : src/WebXLib/Compression.cpp.s

src/WebXLib/Directory.o: src/WebXLib/Directory.cpp.o

.PHONY : src/WebXLib/Directory.o

# target to build an object file
src/WebXLib/Directory.cpp.o:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Directory.cpp.o
.PHONY : src/WebXLib/Directory.cpp.o

src/WebXLib/Directory.i: src/WebXLib/Directory.cpp.i

.PHONY : src/WebXLib/Directory.i

# target to preprocess a source file
src/WebXLib/Directory.cpp.i:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Directory.cpp.i
.PHONY : src/WebXLib/Directory.cpp.i

src/WebXLib/Directory.s: src/WebXLib/Directory.cpp.s

.PHONY : src/WebXLib/Directory.s

# target to generate assembly for a file
src/WebXLib/Directory.cpp.s:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Directory.cpp.s
.PHONY : src/WebXLib/Directory.cpp.s

src/WebXLib/HTTP.o: src/WebXLib/HTTP.cpp.o

.PHONY : src/WebXLib/HTTP.o

# target to build an object file
src/WebXLib/HTTP.cpp.o:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/HTTP.cpp.o
.PHONY : src/WebXLib/HTTP.cpp.o

src/WebXLib/HTTP.i: src/WebXLib/HTTP.cpp.i

.PHONY : src/WebXLib/HTTP.i

# target to preprocess a source file
src/WebXLib/HTTP.cpp.i:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/HTTP.cpp.i
.PHONY : src/WebXLib/HTTP.cpp.i

src/WebXLib/HTTP.s: src/WebXLib/HTTP.cpp.s

.PHONY : src/WebXLib/HTTP.s

# target to generate assembly for a file
src/WebXLib/HTTP.cpp.s:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/HTTP.cpp.s
.PHONY : src/WebXLib/HTTP.cpp.s

src/WebXLib/Interception.o: src/WebXLib/Interception.cpp.o

.PHONY : src/WebXLib/Interception.o

# target to build an object file
src/WebXLib/Interception.cpp.o:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Interception.cpp.o
.PHONY : src/WebXLib/Interception.cpp.o

src/WebXLib/Interception.i: src/WebXLib/Interception.cpp.i

.PHONY : src/WebXLib/Interception.i

# target to preprocess a source file
src/WebXLib/Interception.cpp.i:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Interception.cpp.i
.PHONY : src/WebXLib/Interception.cpp.i

src/WebXLib/Interception.s: src/WebXLib/Interception.cpp.s

.PHONY : src/WebXLib/Interception.s

# target to generate assembly for a file
src/WebXLib/Interception.cpp.s:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Interception.cpp.s
.PHONY : src/WebXLib/Interception.cpp.s

src/WebXLib/Logarithm.o: src/WebXLib/Logarithm.cpp.o

.PHONY : src/WebXLib/Logarithm.o

# target to build an object file
src/WebXLib/Logarithm.cpp.o:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Logarithm.cpp.o
.PHONY : src/WebXLib/Logarithm.cpp.o

src/WebXLib/Logarithm.i: src/WebXLib/Logarithm.cpp.i

.PHONY : src/WebXLib/Logarithm.i

# target to preprocess a source file
src/WebXLib/Logarithm.cpp.i:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Logarithm.cpp.i
.PHONY : src/WebXLib/Logarithm.cpp.i

src/WebXLib/Logarithm.s: src/WebXLib/Logarithm.cpp.s

.PHONY : src/WebXLib/Logarithm.s

# target to generate assembly for a file
src/WebXLib/Logarithm.cpp.s:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Logarithm.cpp.s
.PHONY : src/WebXLib/Logarithm.cpp.s

src/WebXLib/Sockets.o: src/WebXLib/Sockets.cpp.o

.PHONY : src/WebXLib/Sockets.o

# target to build an object file
src/WebXLib/Sockets.cpp.o:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Sockets.cpp.o
.PHONY : src/WebXLib/Sockets.cpp.o

src/WebXLib/Sockets.i: src/WebXLib/Sockets.cpp.i

.PHONY : src/WebXLib/Sockets.i

# target to preprocess a source file
src/WebXLib/Sockets.cpp.i:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Sockets.cpp.i
.PHONY : src/WebXLib/Sockets.cpp.i

src/WebXLib/Sockets.s: src/WebXLib/Sockets.cpp.s

.PHONY : src/WebXLib/Sockets.s

# target to generate assembly for a file
src/WebXLib/Sockets.cpp.s:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/Sockets.cpp.s
.PHONY : src/WebXLib/Sockets.cpp.s

src/WebXLib/VirtualHosts.o: src/WebXLib/VirtualHosts.cpp.o

.PHONY : src/WebXLib/VirtualHosts.o

# target to build an object file
src/WebXLib/VirtualHosts.cpp.o:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/VirtualHosts.cpp.o
.PHONY : src/WebXLib/VirtualHosts.cpp.o

src/WebXLib/VirtualHosts.i: src/WebXLib/VirtualHosts.cpp.i

.PHONY : src/WebXLib/VirtualHosts.i

# target to preprocess a source file
src/WebXLib/VirtualHosts.cpp.i:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/VirtualHosts.cpp.i
.PHONY : src/WebXLib/VirtualHosts.cpp.i

src/WebXLib/VirtualHosts.s: src/WebXLib/VirtualHosts.cpp.s

.PHONY : src/WebXLib/VirtualHosts.s

# target to generate assembly for a file
src/WebXLib/VirtualHosts.cpp.s:
	$(MAKE) -f CMakeFiles/WebXO.dir/build.make CMakeFiles/WebXO.dir/src/WebXLib/VirtualHosts.cpp.s
.PHONY : src/WebXLib/VirtualHosts.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... WebXO"
	@echo "... src/WebXLib/Compression.o"
	@echo "... src/WebXLib/Compression.i"
	@echo "... src/WebXLib/Compression.s"
	@echo "... src/WebXLib/Directory.o"
	@echo "... src/WebXLib/Directory.i"
	@echo "... src/WebXLib/Directory.s"
	@echo "... src/WebXLib/HTTP.o"
	@echo "... src/WebXLib/HTTP.i"
	@echo "... src/WebXLib/HTTP.s"
	@echo "... src/WebXLib/Interception.o"
	@echo "... src/WebXLib/Interception.i"
	@echo "... src/WebXLib/Interception.s"
	@echo "... src/WebXLib/Logarithm.o"
	@echo "... src/WebXLib/Logarithm.i"
	@echo "... src/WebXLib/Logarithm.s"
	@echo "... src/WebXLib/Sockets.o"
	@echo "... src/WebXLib/Sockets.i"
	@echo "... src/WebXLib/Sockets.s"
	@echo "... src/WebXLib/VirtualHosts.o"
	@echo "... src/WebXLib/VirtualHosts.i"
	@echo "... src/WebXLib/VirtualHosts.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

